### PR TITLE
Avoid "ad" when creating a directory path

### PR DESCRIPTION
**Pull request by fitodic**

### CODE REVIEW

**Comment by mislavcimpersak** [comment]
@fitodic please check while tests are failing.

**Comment by mislavcimpersak** [comment]
@Ylodi & @ajhi this looks ok for me. when both of you agree with new code, will merge it.

**Comment by fitodic** [comment]
@mislavcimpersak There was a minor bug in the default parameters when creating test images.

**Comment by Ylodi** [comment]
@fitodic please can You fix this exception handling for Python3 -  models.py - line 115

**Comment by fitodic** [comment]
@Ylodi Fixed exception syntax.

**Comment by mislavcimpersak** [comment]
Perhaps all this hash generating is overcomplicated :-/

```
from django.utils.crypto import get_random_string

get_random_string(4, '0123456789bcefghijklmnop')
```

With omitting "a" and "d" or just one we'll never get "ad/" as part of path. 

Food for thought

**Comment by fitodic** [comment]
@Ylodi What do you say about @mislavcimpersak 's suggestion? Should we implement it?

**Comment by Ylodi** [comment]
Is this get_random_string random enough (without repetition)? :-)

Or You can just replace ad in hash with ag (or some other character which is not a..f)?

**Comment by mislavcimpersak** [comment]
Did some testing for randomness just now (I just dropped `d` from the alphabet)

```
from django.utils.crypto import get_random_string

l = []
for i in range(1000):
    for i in range(10):
        l.append(get_random_string(4, '0123456789abcefghijklmnopqrstuvwxyz'))
print len(l), len(set(l))

>>> 10000 9975
```

And this difference is because of short string (only 4 chars).

I'm not for simple replacing because more images will be in dir `ag/` then in other dirs if we drop `ad/` dir that way.

**Comment by mislavcimpersak** [comment]
looks good.

@Ylodi please merge if you agree with fix.

**Comment by fitodic** [comment]
@Ylodi Please have a look at the latest changes.

**Pull request merged**
